def label = "135.251.206.37"
podTemplate(
    label: label, 
    cloud: 'kubernetes',
    containers: [
        containerTemplate(name: 'jnlp-slave', image: 'cnych/jenkins:v1')
    ],
    volumes: [
        hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
        hostPathVolume(mounntPath:'/usr/bin/docker',hostPath:'/usr/bin/docker')
    ])
    {
        //node = the pod label
        node(label){
            stage('get a maven project'){
                container(label){
                    stage('wait for exec check'){
                        sh 'sleep 1'
                        sh 'echo $JAVA_HOME'
                        sh 'mvn -v'
                    }
                    stage('get maven env'){
                        sh 'cat /etc/resolv.conf'
                        sh 'cat /etc/issue'
                        sh 'uname -a'
                        sh 'env'
                    }
                }
            }
        }
    }
