
- hosts: 135.251.206.38
  gather_facts: false
  tasks:
    - name: get openssl version 
      shell: openssl version | awk -F ' ' '{if($2=="1.0.1e-fips" || $2=="1.0.2k-fips"){print "0"}else{print "1"}}'
      register: openssl_result
      tags:
        - test
    - name: check openssl version
      shell: echo "hi"
      when: openssl_result.stdout.find('0') != -1

    - name: get libssl.so
      shell: ll /usr/lib/libssl.so >/dev/null 2>&1;echo $?
      register: get_result
      tags:
        - check
    - name: check libssl.so
      shell: echo "hi"
      when: get_result.stdout.find('127') != -1

    - name: get ifconfig-eth
      shell: ll /etc/sysconfig/network-scripts/ifcfg-e*  | awk -F '/' '{if($5=="eth0"){print "0"}else{print "1"}}'
      register: ifconfig_result
      tags:
        - get ifconfig-eth
    - name: check ifconfig-eth
      shell: echo "hi"
      when: ifconfig_result.stdout.find('0') != -1
